check

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,27 @@
 #!/usr/bin/env bash
-# Write a Bash script that transfers a file from our client to a servers
+# checking for command line arguments
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
-else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+if [ $# -lt 4 ]
+then
+		echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+		exit 1
 fi
+
+# assigning paramentals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabbling strict host key checking
+
+scp -o "SrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+
+# checking if the file transfer was succesful
+if [ $? -eq 0]
+then
+		echo "FILE WAS TRANSFERED SUCCESFULLY"
+else
+		echo "FILE TRANSFER FAILED"
